packages:
  - packages/*

catalog:
  '@tiptap/core': ^3.13.0
  '@types/lodash': ^4.17.23
  '@types/node': ^22.19.11
  '@types/react': ^19.2.4
  '@types/react-dom': ^19.2.3
  lodash: ^4.17.23
  react: ^19.2.4
  react-dom: ^19.2.4
  tailwindcss: ^4.1.14
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.1.9
  vitest: ^3.2.4

onlyBuiltDependencies:
  - '@swc/core'
  - electron
  - electron-winstaller
  - esbuild
