/**
 * Constant names for use with IPC
 */
export enum ChannelNames {
  CREATE_NOTE = "create-note",
  SET_JSON_CONTENT = "set-json-content",
  GET_JSON_CONTENT = "get-json-content",
  DELETE_NOTE = "delete-note",
  MOVE_NOTE = "move-note",
  UPDATE_NOTE = "update-note",
  GET_ALL_NOTES = "get-all-notes",
  SET_TRASH_STATUS = "set-trash-status",
  SAVE_USER_PREFS = "save-user-settings",
  LOAD_USER_PREFS = "load-user-settings",
  GET_NOTE = "get-note",
  SAVE_NOTES = "save-notes",
  EXPORT_NOTE = "export-note",
  IMPORT_HTML = "import-html",
  SHOW_APP_MENU = "show-app-menu",
  GET_APP_INFO = "get-app-info",
  INIT_EXPORT_CACHE = "init-export-cache",
  PUSH_EXPORT_DOCUMENT = "push-export-document",
  FINISH_EXPORT = "finish-export",
  BACKUP_USER_DATA = "backup-user-data",
  OPEN_BACKUP = "choose-backup-file",
  RESTORE_BACKUP = "restore-user-data",
  IMPORT_THEME = "import-theme",
  LOAD_THEMES = "load-themes",
  SET_TITLEBAR_SYMBOL_COLOR = "set-titlebar-symbol-color",
  RESOLVE_EMBED = "resolve-embed",
  UPLOAD_EMBED = "upload-embed",
  UPLOAD_EMBED_WITH_BUFFER = "upload-embed-with-buffer",
  GET_ACCENT_COLOR = "get-accent-color",
  IMPORT_NOTE = "import-note",
}
