import _ from "lodash";
import type { NoteDTO } from "./note";
import { Rank } from "./rank";

export interface IdRankPair {
  id: string;
  rank: string;
}

type OrderHintKey = "orderHint" | "favoriteOrderHint";
export const ANCHOR_ELEMENT_ID = "ANCHOR";

function convertToIdRankPair(notes: NoteDTO[], key: OrderHintKey) {
  return notes
    .map((n) => ({ id: n.id, rank: n[key] }))
    .toSorted((a, b) => Rank.sorter(a.rank, b.rank)) satisfies IdRankPair[];
}

function convertIdRankPairToChangeset(items: IdRankPair[], key: OrderHintKey) {
  return items.map((e) => ({ id: e.id, [key]: e.rank }));
}

/**
 * Finds colliding ranks in the given list. **Items must be sorted in advance before calling this method!**
 * @param items
 * @returns a list of collision groups. In each collision group, the first element is the predecessor to the colliding elements.
 */
export function identifyCollisions(items: IdRankPair[]): IdRankPair[][] {
  if (items.length < 2) return [];
  const groupList = [];
  let currentCollisionGroup: IdRankPair[] = [];
  for (let i = 1; i < items.length; i++) {
    const previous = items[i - 1];
    const current = items[i];
    if (previous.rank !== current.rank) {
      if (currentCollisionGroup.length === 0) continue; // no collision chain

      // chain broken, save group and continue
      groupList.push(currentCollisionGroup);
      currentCollisionGroup = [];
      continue;
    }
    if (i === 1) {
      // there's collision at list start, anchor element will be used
      const anchor: IdRankPair = {
        id: ANCHOR_ELEMENT_ID,
        rank: Rank.default().get(),
      };
      currentCollisionGroup.push(anchor, previous, current);
      groupList.push(currentCollisionGroup);
      currentCollisionGroup = [];
      continue;
    }
    if (currentCollisionGroup.length > 0) {
      // this is an ongoing collision, we'll push the current and continue
      currentCollisionGroup.push(current);
      continue;
    }
    // we are initializing a new group
    const twoBefore = items[i - 2];
    currentCollisionGroup.push(twoBefore, previous, current);
  }

  if (currentCollisionGroup.length > 0) groupList.push(currentCollisionGroup);
  return groupList;
}

/**
 * Fixes all collisions in a collision set generated by `identifyCollisions`
 * @param items a single group outputted by `identifyCollisions`. The group must have at least 3 elements - as specified by the realted method.
 * @returns the items with fixed ranks. The first element (the healthy element) **will be removed** from the output set.
 * An empty array will be returned if the group has less than 3 elements.
 */
export function fixCollisionsInGroup(items: IdRankPair[]): IdRankPair[] {
  if (items.length < 3) return [];
  const outputList: IdRankPair[] = items.map((i) => _.clone(i));
  for (let i = 1; i < outputList.length; i++) {
    const item = outputList[i];
    const previous = outputList[i - 1];
    const currentRank = new Rank(item.rank);
    const previousRank = new Rank(previous.rank);
    const middle = currentRank.between(previousRank);
    item.rank = middle.toString();
  }
  outputList.splice(0, 1); // remove anchor element
  return outputList;
}

export function generateRankCollisionChangeset(
  notes: NoteDTO[],
  key: OrderHintKey,
) {
  // We can't have a collision with less than 2 notes
  if (notes.length < 2) return [];

  const items = convertToIdRankPair(notes, key);
  const collisionGroups = identifyCollisions(items);
  const changeSet: IdRankPair[] = [];
  for (const collisionSet of collisionGroups) {
    const fixedSet = fixCollisionsInGroup(collisionSet);
    changeSet.push(...fixedSet);
  }
  const patchSet = convertIdRankPairToChangeset(changeSet, key);
  return patchSet;
}
