name: "release"
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CI: false

jobs:
  build:
    name: "Build desktop"
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{matrix.platform}}
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: corepack enable
      - name: Install dependencies
        run: pnpm install

      - name: Linter check
        run: pnpm lint

      - name: Install Python dependencies (macOS)
        run: |
          brew install python-setuptools
        if: runner.os == 'macOS'

      - name: Install Python dependencies (Windows)
        run: |
          pip install setuptools
        if: runner.os == 'Windows'

      - name: Build
        run: pnpm build:desktop
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            packages/app-desktop/release/*/Darkwrite-*.exe
            packages/app-desktop/release/*/Darkwrite-*.dmg
            packages/app-desktop/release/*/Darkwrite-*.AppImage
            packages/app-desktop/release/*/Darkwrite-*.deb
            packages/app-desktop/release/*/Darkwrite-*.tar.zst
            packages/app-desktop/release/*/Darkwrite-*.rpm
          draft: true
