name: "release"
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CI: false
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build:
    name: "Build desktop"
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, windows-latest] # macOS temporarily removed until CI notarization is ready
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Linter check
        run: pnpm lint

      - name: Install Python dependencies (macOS)
        run: |
          brew install python-setuptools
        if: runner.os == 'macOS'

      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        if: runner.os == 'macOS'

      - name: Install Python dependencies (Windows)
        run: |
          pip install setuptools
        if: runner.os == 'Windows'

      - name: Build
        run: pnpm build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            packages/app-desktop/release/*/*.exe
            packages/app-desktop/release/*/*.dmg
            packages/app-desktop/release/*/*.AppImage
            packages/app-desktop/release/*/*.deb
            packages/app-desktop/release/*/*.tar.zst
            packages/app-desktop/release/*/*.rpm
          draft: true
