name: tests and linting
on:
  push:
    branches:
      - dev
    paths:
      - "app/src/**/*"
      - "app/pnpm-lock.yaml"
      - "app/package.json"
      - "!*.md"
      - "!./**/*.md"
      - ".github/workflows/test-unit.yml"
  workflow_dispatch:

env:
  CI: false
  ELECTRON_SKIP_BINARY_DOWNLOAD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    name: unit/integration tests and type checking

    steps:
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Ensure better-sqlite3 is built
        run: pnpm --filter=@darkwrite/app-desktop rebuild better-sqlite3

      - name: Lint
        run: pnpm lint
        if: always()

      - name: Check types
        run: pnpm typecheck
        if: always()

      - name: Run tests
        run: pnpm test
        if: always()


