name: tests and linting
on:
  push:
    branches:
      - dev
    paths:
      - "packages/*/src/**/*"
      - "yarn.lock"
      - "package.json"
      - "packages/*/package.json"
      - "!*.md"
      - "!./**/*.md"
      - ".github/workflows/test-unit.yml"
  workflow_dispatch:

env:
  CI: false
  ELECTRON_SKIP_BINARY_DOWNLOAD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    name: unit tests and type checking
    steps:
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Build @darkwrite/common
        run: yarn workspace "@darkwrite/common" build

      - name: Build @darkwrite/ui
        run: yarn workspace "@darkwrite/ui" build

      - name: Lint
        run: yarn lint
        if: always()

      - name: Check types
        run: yarn typecheck
        if: always()

      # - name: Run tests
      #   run: yarn test
      #   if: always()


